apiVersion: v1
kind: Service
metadata:
  name: progress-service
spec:
  selector:
    app: progress-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30002