apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
        - name: progress-container
          image: progress-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker